# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.BooleanField()),
                ('pets', models.BooleanField()),
                ('cable', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('smoking', models.BooleanField()),
                ('electric', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('reservedParking', models.BooleanField()),
                ('coveredParking', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('rating', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('leasingOptions', models.CharField(max_length=255)),
                ('bedrooms', models.PositiveIntegerField()),
                ('amenities', models.ManyToManyField(to='apartments.Amenities')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contactInfo', models.CharField(max_length=255)),
                ('distanceToCity', models.BooleanField()),
                ('distanceToEast', models.BooleanField()),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('apartmentPreferences', models.ManyToManyField(to='apartments.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noise', models.PositiveIntegerField()),
                ('social_academic', models.PositiveIntegerField()),
                ('temp', models.PositiveIntegerField()),
                ('cleanliness', models.PositiveIntegerField()),
                ('visitors', models.PositiveIntegerField()),
                ('drinking', models.PositiveIntegerField()),
                ('smoking', models.CharField(max_length=255)),
                ('sleepTime', models.CharField(max_length=255)),
                ('durationOfStayMonths', models.PositiveIntegerField()),
                ('interests', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('hospitality', models.PositiveIntegerField()),
                ('maintenance', models.PositiveIntegerField()),
                ('safety_security', models.PositiveIntegerField()),
                ('overall', models.PositiveIntegerField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Building')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.People')),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Profile'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Building'),
        ),
    ]
