# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_auto_20170314_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='rating',
        ),
        migrations.AddField(
            model_name='building',
            name='amenities',
            field=models.ManyToManyField(to='apartments.Amenities'),
        ),
        migrations.AddField(
            model_name='building',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
