# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_auto_20170315_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='apartment',
            new_name='building',
        ),
        migrations.AddField(
            model_name='building',
            name='name_slug',
            field=models.SlugField(default='building-name'),
        ),
    ]
